language: rust
rust: stable

install:
  - rustup target add thumbv7em-none-eabi
  - rustup target add thumbv6m-none-eabi
  - rustup component add rustfmt

stages:
  - test
  - name: deploy
    if: branch = master AND type = push

jobs:
  include:
    - stage: test
      script: ci/test.sh
    - stage: deploy
      env:
        TARGET: thumbv7em-none-eabi
      script:
        - cargo doc --no-deps --target=$TARGET
        - echo "<meta http-equiv=refresh content=0;url=rubble/index.html>" > target/$TARGET/doc/index.html
        - sudo pip install ghp-import
        - ghp-import -n target/$TARGET/doc
        - git push -qf https://${GH_TOKEN}@github.com/jonas-schievink/rubble.git gh-pages

notifications:
  email:
    on_success: never
